### ISSUE TITLE
Issue setting username and password

### ISSUE THREAD

**Issue by Farfaday** [innogames/graphite-ch-optimizer#12]
Hi !
I have been trying without success to set username and password in the server-dsn variable:

`  server-dsn = "tcp://localhost:9000?&optimize_throw_if_noop=1&receive_timeout=3600&debug=true&user=xxxxx&password=xxxxxx"`

But starting   

```
 graphite-ch-optimizer -n --log-level debug -c config.toml

[clickhouse]host(s)=localhost:9000, database=default, username=default
[clickhouse][dial] secure=false, skip_verify=false, strategy=random, ident=1, server=0 -> 127.0.0.1:9000
[clickhouse][connect=1][hello] -> Golang SQLDriver 1.1.54213
```

I still get username "default" here.
Does someone have any hint ?
Thanks!

**Comment by Felixoid** [comment]
Hey. Here's [a manual](https://github.com/ClickHouse/clickhouse-go#dsn) how to set DSN

**Comment by Farfaday** [comment]
haaa ! Many thanks ! It is able to connect now !
