### ISSUE TITLE
Option --optimize-interval is confusive

### ISSUE THREAD

**Issue by Felixoid** [innogames/graphite-ch-optimizer#8]
It tells, that `The active partitions won't be optimized more than once per this interval, seconds`, but:

- The active partition won't be merged unless it was modified during the period
- It's not seconds, but the duration. The same for loop-interval
- There's a mistake in query https://github.com/innogames/graphite-ch-optimizer/blob/master/graphite-ch-optimizer.go#L65. It doesn't make sense to compare `@Interval` option with maximum age for the current retention. The line should be deleted, then all `parts > 1` will proceed.

**Comment by lexx-bright** [comment]
@Felixoid, to comply with the statement 
>-- modified_at < (now() - @Interval): we want to merge active partitions only once per interval,
>--   so do not touch partitions with current active inserts

shouldn't [p.modification_time](https://github.com/innogames/graphite-ch-optimizer/blob/2191d354407102444bc6918ab00f19565b0afc47/graphite-ch-optimizer.go#L38) be maxed?
